steps:
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/stedi-jacob:latest
      - .
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - gcr.io/$PROJECT_ID/stedi-jacob:latest
  - name: gcr.io/cloud-builders/gke-deploy
    id: Deploy
    args:
      - run
      - --filename=manifest.yaml
      - --image=gcr.io/$PROJECT_ID/stedi-jacob:latest
      - --location=us-west1-b
      - --cluster=cluster-2
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/yarn'
    id: Test
    args: ['test']