steps:
  - name: "gcr.io/cloud-builers/docker"
    id: Build
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/stedi-tests-jacob:latest"
      - "."
  - name: "gcr.io/cloud-builers/docker"
    id: Push
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/stedi-tests-jacob:latest"