#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacob-perry-stedi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jacob-perry-stedi
  template:
    metadata:
      labels:
        app: jacob-perry-stedi
    spec:
      containers:
        - name: jacob-perry-stedi
          image: gcr.io/power-glove/stedi-jacob:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".1"
              memory: "500Mi"
            requests:
              cpu: ".1"
              memory: "250Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3
          command: ["yarn"]
          args: ["start"]

---

apiVersion: v1
kind: Service
metadata:
  name: jacob-perry-stedi-loadbalancer
spec:
  selector:
    app: jacob-perry-stedi
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000