#© 2021 Sean Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jacob-perry-stedi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jacob-perry-stedi
  template:
    metadata:
      labels:
        app: jacob-perry-stedi
    spec:
      containers:
        - name: jacob-perry-stedi
          image: gcr.io/power-glove/stedi-jacob:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 3